spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: an293gls

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  flyway:
    enabled: true
    locations: filesystem:src/main/resources/db/migration
    create-schemas: false
    baseline-on-migrate: on

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 911 922 33 44
  email: mss9836@gmail.com
  copyright: Сергей М
  copyrightFrom: 2002

captcha:
  timeToDel: 60 # ! Формат времени для удаления captcha из БД в МИНУТАХ!

server:
  error:
    include-message: always
    include-binding-errors: always




