spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_db?useSSL=false
    username: root
    password: an293gls
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false



  flyway:
    enabled: true
    user: root
    password: an293gls
    schemas: blog_db
    url: jdbc:mysql://localhost:3306/blog_db?useSSL=false
    locations: filesystem:src/main/resources/db/migration
    create-schemas: false
    baseline-on-migrate: off


blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 911 922 33 44
  email: mail@gmail.com
  copyright: Сергей М
  copyrightFrom: 2002



